version: '2.1'
services:
  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/data/db:/data/db
    env_file:
      - ./mongodb/.env
    networks:
      - gateway_app-net

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ~/_logs:/_logs
      - ~/public:/public
    depends_on:
      - mongodb
    networks:
      - gateway_app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000/admin"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  gateway_app-net:
    external: true
