services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ~/_logs:/_logs
      - ~/public:/public
    networks:
      - gateway_app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000/cinefolio/admin"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  gateway_app-net:
    external: true
