version: '2.1'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/data:/data
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    volumes:
      - ~/_logs:/_logs
      - ~/public:/public
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000/admin"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-net:
