name: Deploy to Hostinger

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy file via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "."
        target: "/home/micho/cine"
        rm: true
        overwrite: true
    - name: Set up SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./ssh_key && chmod 600 ./ssh_key
    - name: Run build script on VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        ssh -i ./ssh_key -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'cd /home/micho/cine/ && bash build.sh'
